export * from 'src/app/com/annaniks/dastavok/modals/login/login.modal';
export * from 'src/app/com/annaniks/dastavok/modals/verification/verification.modal';
export * from 'src/app/com/annaniks/dastavok/modals/phone-number/phone-number.modal';
export * from 'src/app/com/annaniks/dastavok/modals/signUp/signUp.modal';
export * from 'src/app/com/annaniks/dastavok/modals/new-passwors/new-password.modal';
export * from 'src/app/com/annaniks/dastavok/modals/user-update/user-update.modal';
export * from "src/app/com/annaniks/dastavok/modals/address-edit/address-edit.modal";
export * from "src/app/com/annaniks/dastavok/modals/registration-step/registration-step.modal";
export * from "src/app/com/annaniks/dastavok/modals/search-goods/search-goods.component";
export *from "src/app/com/annaniks/dastavok/modals/new-phone-number/new-phone-number.modals";
export *from  "src/app/com/annaniks/dastavok/modals/messages/messages.modals";